### ISSUE TITLE
Add package type to composer.json

### ISSUE THREAD

**Issue by dnaber-de** [Savvii/warpdrive#1]
Hi there,

glad to see, the Plugin is now public. That helps to integrate it into Composer built applications. However, the composer.json is right now missing the `type` property. In order to determine the correct install directory the type should be `wordpress-plugin`. See https://getcomposer.org/doc/04-schema.md#type

So the composer.json should look like
```
{
    "name": "savvii/warpdrive",
    "description": "This plugin manages various features used by Savvii",
    "license": "GPLv3",
    "type": "wordpress-plugin",
    "require-dev": {
        "phpunit/phpunit": "4.8.*"
    }
}
```

**Comment by dnaber-de** [comment]
Also, a bugfix release (2.8.4 for example) would help to use proper version constraints (`^2.8`) in any depending project. Otherwise we would have to use `dev-master` which is not a good idea.

**Comment by fuegas** [comment]
@dnaber-de we use [Semantic Versioning](https://semver.org/) for our software, so you can use the version constraints you describe.

**Comment by dnaber-de** [comment]
Generally, this is good to know and of course a good thing. In this case I was asking for a bugfix release when the package type was added.
