### ISSUE TITLE
Cache wordt niet automatisch geleegd bij opslaan custom post type

### ISSUE THREAD

**Issue by danielpost** [Savvii/warpdrive#12]
Hi guys,

Ik had vandaag een issue waarbij een klant nieuw aangemaakte CPT items niet kon zien als hij niet ingelogd was. De cache handmatig flushen loste het probleem op.

Ik heb even gekeken en volgens mij is het automatisch legen van de cache momenteel beperkt tot posts en pages. [Hier](https://github.com/Savvii/warpdrive/blob/master/src/class-cache-flusher-plugin.php#L36) wordt gebruik gemaakt van de `publish_page` en `publish_post` hooks, waardoor custom post types niet worden meegenomen.

Misschien is dit bewust zo, maar persoonlijk lijkt het mij handig om custom post types ook mee te nemen. Een mogelijke oplossing zou zijn om dit toe te voegen onder [regel 104](https://github.com/Savvii/warpdrive/blob/master/src/class-cache-flusher-plugin.php#L104) (niet getest):

```php
foreach ( get_post_types( ['public' => true, '_builtin' => false] ) as $post_type ) {
	add_action( "publish_{$post_type}", [ $this, 'domainflush' ], 10, 2 );
}
```

Bedankt en ik hoor het graag!

**Comment by ghovens** [comment]
Hi Daniel,

Bedankt voor je idee! Klinkt heel erg logisch. Ik heb dit meegenomen op onze backlog. Implementatie is waarschijnlijk niet al te spannend, we moeten vantevoren wat tijd steken in het onderzoeken van de impact en het testen.

Thanks!

**Comment by danielpost** [comment]
Hey Gijs, bedankt voor je reactie! Ik snap dat het wat tijd kost om te implementeren en de bijbehorende tests te schrijven, fijn dat het wordt opgepakt.

Ik gebruik nu zelf deze tijdelijke fix die goed lijkt te werken, misschien handig voor anderen die tegen hetzelfde aanlopen:

```php
/**
 * Force Savvii cache flush when saving a published post.
 * 
 * @link https://github.com/Savvii/warpdrive/issues/12
 * 
 * @param int $post_id
 * @param \WP_Post $post
 */
add_action('save_post', function ($post_id, $post) {
    if ($post->post_status !== 'publish') {
        return;
    }

    do_action('warpdrive_domain_flush');
}, 10, 2);
```

**Comment by joverthegrey** [comment]
Hoi Daniel,

Het duurde even maar release 2.10.5 heeft nu de mogelijkheid om te flushen op custom post types.
