### ISSUE TITLE
Publish plugin on packagist.org

### ISSUE THREAD

**Issue by fuegas** [Savvii/warpdrive#3]
As the plugin is public now and we use [Semantic Versioning](https://semver.org/) for it, we want to publish it on [Packagist](https://packagist.org/) so you can use composer to get the latest version.

**Comment by dnaber-de** [comment]
Very good news. Let me know if I can help you there. In general, the process is pretty straight forward.

**Comment by fuegas** [comment]
The repo has been released on Packagist: https://packagist.org/packages/savvii/warpdrive
Integration should be setup correct as well now so when we create a new release it should update on Packagist as well.

**Comment by lekkerduidelijk** [comment]
Thanks @fuegas!
