### ISSUE TITLE
PHP Notice: Trying to get property 'enabled' of non-object

### ISSUE THREAD

**Issue by erikmolenaarnl** [Savvii/warpdrive#31]
Hi,

Using version 2.10.4 and getting thousands of PHP notices:

Notice:  Trying to get property 'enabled' of non-object in /wp-content/plugins/warpdrive/src/class-cache-flusher-sucuri.php on line 95

Can you fix this in a new version? Thanks.

**Comment by joverthegrey** [comment]
Thanks we'll look into it

**Comment by joverthegrey** [comment]
It is already fixed in the current master and should be in the next release (probably in the next 2 weeks)

**Comment by joverthegrey** [comment]
Fixed in release 2.10.5
