### ISSUE TITLE
Deprecated: Using array_key_exists() on objects is deprecated

### ISSUE THREAD

**Issue by erikmolenaarnl** [Savvii/warpdrive#32]
Hi,

I'm on version 2.10.5, getting these PHP deprecated notices:

`Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /wp-content/plugins/warpdrive/src/class-api-response.php on line 50`

Can you fix this in a next version release? Thanks.

**Comment by dnwjn** [comment]
This is also fixed in #33.
