### ISSUE TITLE
Mogelijkheid om plugin menu item naar settings of tools te verplaatsen

### ISSUE THREAD

**Issue by ericmulder** [Savvii/warpdrive#4]
Is het mogelijk om de plugin als een sub-item van settings of tools te zetten? Dit lijkt me persoonlijk een betere plek, het hoofdmenu wordt al snel zo vol, en het is niet een menu item was in mijn optiek belangrijker is dan het dashboard: https://screencast.com/t/MUzYfwNTW

**Comment by ghovens** [comment]
Hallo Eric,

Dank voor je feedback. We hebben dit in het team besproken en we willen voor een oplossing gaan waarbij de meestgebruikte functies in het topmenu komen middels een drop-down menu (flush cache, view error logs, view access logs). Het Savvii menu item in de zij-navigatie gaat dan helemaal naar beneden, tussen de andere plugins.

Het is echter best wat werk en de meerderheid van onze klanten vraagt ons om andere features. Daarom zullen we dit voorlopig nog niet oppakken. Mocht je het zelf als pull request willen verwerken dan maken we daar natuurlijk wel graag even tijd voor.

Gr. Gijs

**Comment by ericmulder** [comment]
Ik heb een pull request gemaakt waarin ik het menu item tussen de andere items heb gezet. Ik zag dat jullie specifiek de menu order array aanpassen om het menu item altijd bovenaan te zetten. Die heb ik er uit gehaald, en daarnaast gewerkt met de standaard aan te raden priority in de functie.

**Comment by ericmulder** [comment]
Ondertussen is dit verwerkt. Bedankt hiervoor!
